### ISSUE TITLE
Editing a rule usage to a unknown rule should change the coloring and invalidate the symbol reference

### ISSUE THREAD

**Issue by MalteSchledjewski** [pest-parser/intellij-pest#10]
Given a rule `dummy`.
Using `dummy` it is marked as a known rule.
Appending `dbg` to the usage does not make the color change.

Also: as long as the cursor is in the `dummy` part, the other usages of `dummy` are highlighted.

Removing characters or inserting them does also work.

**Comment by ice1000** [comment]
This is probably because I was caching the references. I should do some refactorings on this part.
Thanks for reporting.
