### ISSUE TITLE
[bug] Typo in whitespace builtin name

### ISSUE THREAD

**Issue by mortimr** [pest-parser/intellij-pest#14]
Hi,

I'm currently using your plugin, and the whitespace token is defined in the plugin with the name `WHITESPACE`, while `pest` is defining it with the name `WHITE_SPACE`.

So, I have error highlights on all my `WHITE_SPACE`. And using `WHITESPACE` gives me :
```
  = help: message: grammar error
          
            --> 20:15
             |
          20 | WSDIGITS = _{ WHITESPACE* ~ ASCII_DIGIT+ ~ WHITE_SPACE* }␊
             |               ^--------^
             |
             = rule WHITESPACE is undefined

```

Reference: https://pest.rs/book/grammars/built-ins.html (at the bottom)

Thanks !

**Comment by ice1000** [comment]
Ah. So `WHITESPACE` is used for overwriting, while `WHITE_SPACE` is a built-in rule, right?

I get it. Will fix soon.

**Comment by mortimr** [comment]
Exactly, `WHITESPACE` is used by `pest` and must be defined by the `user`, while `WHITE_SPACE` is a builtin.

Thanks !

**Comment by ice1000** [comment]
Yup I somewhat misunderstood the documentation and I didn't even know that there's such lot of builtin rules. I need to add all of them to the completion list.

**Comment by ice1000** [comment]
I've uploaded an updated version to the plugin repository. The incorrect highlight will get out of your sight and you'll see completions with all those builtin rules.
Here's a list of builtin rules I've added just now:

https://github.com/pest-parser/intellij-pest/blob/d3be5c14fac67e7572936b4c12e58f85382b6e0a/src/rs/pest/pest-constants.kt#L20-L130

Cheers!

**Comment by mortimr** [comment]
Great !

Thank you for your amazing work ! 👍
