### ISSUE TITLE
Cannot parse rules that uses `COMMENT` and `WHITESPACE`

### ISSUE THREAD

**Issue by mortimr** [pest-parser/intellij-pest#15]
Hi !

The rules `COMMENT` and `WHITESPACE` seem to be defined as globally available rules.
The thing is that both `COMMENT` and `WHITESPACE` are indeed special rules that are used by `pest`, but one important thing is that they can be user defined.

With `0.1.6` I get 

<img width="442" alt="Screen Shot 2019-03-30 at 3 10 36 PM" src="https://user-images.githubusercontent.com/17824082/55280591-117baf00-52fe-11e9-98c1-8dbb7807c44a.png">

when I define my own `COMMENT` rules.

Is there a way to add mutability to these global rules ?

**Comment by ice1000** [comment]
Do you get syntax errors elsewhere?

I have the same problem in my project minitt-rs. I've fixed this in version 0.1.7, which is pending JetBrains approval right now. Could you please reply this thread when you update to 0.1.7?

**Comment by ice1000** [comment]
This happens because another bug fix in 0.1.6 changes the parser, causing that it cannot parse rules that **uses** `COMMENT` and `WHITESPACE`.
Overwriting them won't cause a problem.

**Comment by mortimr** [comment]
No more errors with `0.1.7` ! Thanks !
