### ISSUE TITLE
Peek with slice is reported as syntax error

### ISSUE THREAD

**Issue by flying-sheep** [pest-parser/intellij-pest#39]
With the grammar

```pest
test = _{ PEEK[..] ~ "test" }
```

I get

```
at 1:16 MINUS or NUMBER expected, got '..'
at 1:18 MINUS OR NUMBER expected, got ']'
```

**Comment by ice1000** [comment]
Does this compile with pest's rust implementation?

**Comment by flying-sheep** [comment]
Of course. Here’s a stupid example that works:

https://pest.rs/?bin=1976tc#editor

**Comment by flying-sheep** [comment]
Here’s where the error is added to the builder:

![grafik](https://user-images.githubusercontent.com/291575/71680311-04f31e00-2d8a-11ea-8936-4cae14ba32d1.png)
